name = "stockanalysis-cf"
type = "javascript"
zone_id = ""
account_id = "52fc8659ba03bc08639c74adc9d487db"
route = ""
workers_dev = true
compatibility_date = "2021-11-23"
preview_id = "32f9f8fb17564cf99da0ef182f351f89"

kv_namespaces = [ 
  { binding = "Index", preview_id = "32f9f8fb17564cf99da0ef182f351f89", id = "1fdbb62567944e038f99db8982183996" }
]

[vars]
AIRTABLE_BASE_ID = "appmFW8uGB0wOxO7y"
AIRTABLE_API_KEY = "keyJ5bw05Jnmjjuee"
SA_CF_KEY = "4ba6c01110f195581e5575afe2d731902ca93"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
